name: Parse Frontmatter from MD Files

on:
  push:

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install necessary packages
      run: sudo apt-get install -y python3-pip && pip3 install pyyaml

    - name: Create output directory
      run: mkdir -p output

    - name: Extract and Parse Frontmatter
      run: python3 .github/scripts/parse_all_yaml_to_json.py
    - name: Archive output directory
      uses: actions/upload-artifact@v2
      with:
           name: output
           path: ./output/
